// Словарь англ. → рус. названий сборных. Ключ — англ. название из football-data.org.
// Покрываем заведомо больше 48 участников ЧМ-2026, чтобы не зависеть от точного списка.
export const TEAMS_RU: Record<string, string> = {
  Argentina: "Аргентина",
  Australia: "Австралия",
  Austria: "Австрия",
  Belgium: "Бельгия",
  Bolivia: "Боливия",
  Brazil: "Бразилия",
  Cameroon: "Камерун",
  Canada: "Канада",
  Chile: "Чили",
  Colombia: "Колумбия",
  "Costa Rica": "Коста-Рика",
  "Ivory Coast": "Кот-д’Ивуар",
  "Côte d'Ivoire": "Кот-д’Ивуар",
  Croatia: "Хорватия",
  "Czech Republic": "Чехия",
  Czechia: "Чехия",
  Denmark: "Дания",
  Ecuador: "Эквадор",
  Egypt: "Египет",
  England: "Англия",
  France: "Франция",
  Germany: "Германия",
  Ghana: "Гана",
  Greece: "Греция",
  Honduras: "Гондурас",
  Hungary: "Венгрия",
  Iran: "Иран",
  "IR Iran": "Иран",
  Italy: "Италия",
  Jamaica: "Ямайка",
  Japan: "Япония",
  Mexico: "Мексика",
  Morocco: "Марокко",
  Netherlands: "Нидерланды",
  "New Zealand": "Новая Зеландия",
  Nigeria: "Нигерия",
  Norway: "Норвегия",
  Panama: "Панама",
  Paraguay: "Парагвай",
  Peru: "Перу",
  Poland: "Польша",
  Portugal: "Португалия",
  Qatar: "Катар",
  "Republic of Ireland": "Ирландия",
  Romania: "Румыния",
  "Saudi Arabia": "Саудовская Аравия",
  Scotland: "Шотландия",
  Senegal: "Сенегал",
  Serbia: "Сербия",
  Slovakia: "Словакия",
  Slovenia: "Словения",
  "South Africa": "ЮАР",
  "South Korea": "Южная Корея",
  "Korea Republic": "Южная Корея",
  Spain: "Испания",
  Sweden: "Швеция",
  Switzerland: "Швейцария",
  Tunisia: "Тунис",
  Turkey: "Турция",
  Türkiye: "Турция",
  Ukraine: "Украина",
  "United States": "США",
  USA: "США",
  Uruguay: "Уругвай",
  Uzbekistan: "Узбекистан",
  Venezuela: "Венесуэла",
  Wales: "Уэльс",
  "Bosnia-Herzegovina": "Босния и Герцеговина",
  "Bosnia and Herzegovina": "Босния и Герцеговина",
  Haiti: "Гаити",
  "Curaçao": "Кюрасао",
  Curacao: "Кюрасао",
  "Cape Verde Islands": "Кабо-Верде",
  "Cape Verde": "Кабо-Верде",
  Iraq: "Ирак",
  Algeria: "Алжир",
  Jordan: "Иордания",
  "Congo DR": "ДР Конго",
  "DR Congo": "ДР Конго",
};

/** Рус. название по англ., либо null если нет в словаре. */
export function ruName(englishName: string): string | null {
  return TEAMS_RU[englishName] ?? null;
}
